name: papertheatre
version: 1.0
api-version: 1.19
author: MCMDEV
main: de.mcmdev.theatre.paper.platform.PaperTheatre

commands:
  theatre:
    description: Manage theatre scripts
    permission: theatre.use